all : 
2 	@echo "# Peer-graded Assignment: Bash, Make, Git, and GitHub" > README.md 
3 	@echo -n "The number of lines of code contained in **guessinggame.sh** is " >> README.md 
4 	@cat guessinggame.sh | wc -l  >> README.md 
5 	@echo -n "\nThe date and time at which **make** was run: " >> README.md 
6 	@date >> README.md 
